all:
	g++ -Wall -lGL -lglut -DGL_GLEXT_PROTOTYPES -lfftw3 -lopenal -o MengerSponge\
		mengerSponge.cpp GL_utilities.c VectorUtils2.c loadobj.c LoadTGA.c Cube.cpp AudioPlayer.cpp

clean:
	rm mengerSponge

